### PR TITLE
Fixes / Changes to OtterEntity

### PR DESCRIPTION
**Pull request by Jiingy**
Updated OtterEntityModel to cleaner format
Fixed clipping issue with OtterEntityModel foot parts

### CODE REVIEW

**Comment by Jiingy** [comment]
Currently breeding is implemented, but it spawns the child entity with an adult model, working on fix

**Comment by KaiAF** [comment]
good refactors, only issue I can see by glancing at the code is the mod ID should be ottah

**Comment by Jiingy** [comment]
I think MOD_ID has to be "livzmc" currently due to the file path here, if you do want it to be ottah then this folder I think would have to change too. When the ID is used in paths to textures, if the mod is different to the file path it won't be able to fix a texture properly
image

**Comment by Jiingy** [comment]
This should be everything

**Pull request merged**
